FROM node:20-alpine

WORKDIR /usr/src/app

# Copy only package files for better caching
COPY package*.json ./
COPY .env.example ./.env

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev:docker"]